# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/decoder2to4/decoder2to4.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4 || ORIG_REF_NAME==decoder2to4} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_and2_0_0/decoder2to4_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_and2_0_0 || ORIG_REF_NAME==decoder2to4_xup_and2_0_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_and2_1_0/decoder2to4_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_and2_1_0 || ORIG_REF_NAME==decoder2to4_xup_and2_1_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_and2_2_0/decoder2to4_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_and2_2_0 || ORIG_REF_NAME==decoder2to4_xup_and2_2_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_and2_3_0/decoder2to4_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_and2_3_0 || ORIG_REF_NAME==decoder2to4_xup_and2_3_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_inv_0_0/decoder2to4_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_inv_0_0 || ORIG_REF_NAME==decoder2to4_xup_inv_0_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_inv_1_0/decoder2to4_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_inv_1_0 || ORIG_REF_NAME==decoder2to4_xup_inv_1_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_and2_4_0/decoder2to4_xup_and2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_and2_4_0 || ORIG_REF_NAME==decoder2to4_xup_and2_4_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_and2_5_0/decoder2to4_xup_and2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_and2_5_0 || ORIG_REF_NAME==decoder2to4_xup_and2_5_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_and2_6_0/decoder2to4_xup_and2_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_and2_6_0 || ORIG_REF_NAME==decoder2to4_xup_and2_6_0} -quiet] -quiet

# IP: bd/decoder2to4/ip/decoder2to4_xup_and2_7_0/decoder2to4_xup_and2_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==decoder2to4_xup_and2_7_0 || ORIG_REF_NAME==decoder2to4_xup_and2_7_0} -quiet] -quiet

# XDC: bd/decoder2to4/decoder2to4_ooc.xdc
