-- Testbench automatically generated online
-- at https://vhdl.lapinoo.net
-- Generation date : 6.1.2021 10:24:50 UTC

library ieee;
use ieee.std_logic_1164.all;

entity tb_design_1_wrapper is
end tb_design_1_wrapper;

architecture tb of tb_design_1_wrapper is

    component design_1_wrapper
        port (AT0       : out std_logic;
              AT1       : out std_logic;
              AT2       : out std_logic;
              CMD       : out std_logic;
              CMU       : out std_logic;
              DRC       : out std_logic;
              DRO       : out std_logic;
              FC0       : in std_logic;
              FC2       : in std_logic;
              FCD1      : in std_logic;
              FCU1      : in std_logic;
              GT0       : in std_logic;
              GT1       : in std_logic;
              GT2       : in std_logic;
              clk       : in std_logic;
              en        : in std_logic;
              reset     : in std_logic;
              enabling : in std_logic);
    end component;

    signal AT0       : std_logic;
    signal AT1       : std_logic;
    signal AT2       : std_logic;
    signal CMD       : std_logic;
    signal CMU       : std_logic;
    signal DRC       : std_logic;
    signal DRO       : std_logic;
    signal FC0       : std_logic;
    signal FC2       : std_logic;
    signal FCD1      : std_logic;
    signal FCU1      : std_logic;
    signal GT0       : std_logic;
    signal GT1       : std_logic;
    signal GT2       : std_logic;
    signal clk       : std_logic;
    signal en        : std_logic;
    signal reset     : std_logic;
    signal enabling : std_logic;

    constant TbPeriod : time := 1000 ms; -- EDIT Put right period here
    signal TbClock : std_logic := '0';
    signal TbSimEnded : std_logic := '0';

begin

    dut : design_1_wrapper
    port map (AT0       => AT0,
              AT1       => AT1,
              AT2       => AT2,
              CMD       => CMD,
              CMU       => CMU,
              DRC       => DRC,
              DRO       => DRO,
              FC0       => FC0,
              FC2       => FC2,
              FCD1      => FCD1,
              FCU1      => FCU1,
              GT0       => GT0,
              GT1       => GT1,
              GT2       => GT2,
              clk       => clk,
              en        => en,
              reset     => reset,
              enabling => enabling);

    -- Clock generation
    TbClock <= not TbClock after TbPeriod/2 when TbSimEnded /= '1' else '0';

    -- EDIT: Check that clk is really your main clock signal
    clk <= TbClock;

    stimuli : process
    begin
        -- EDIT Adapt initialization as needed
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        en <= '0';
        enabling <= '0';

        -- Reset generation
        -- EDIT: Check that reset is really your reset signal
        reset <= '1';
        wait for TbPeriod;
        reset <= '0';
        wait for TbPeriod;

        -- EDIT Add stimuli here
       
        en<='1';
        enabling <= '1';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        
         --Default state
         
         
         en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;      
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 1
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 2
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 3
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 4
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '1';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 5
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '1';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '1';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '1';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 6
        en<='1';
        enabling <= '0';
        FC0 <= '1';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '1';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '1';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 7
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '1';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 8
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 9
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '1';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 10
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '1';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 11
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '1';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '1';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '1';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '1';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 12
        en<='1';
        enabling <= '0';
        FC0 <= '1';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        en<='1';
        enabling <= '0';
        FC0 <= '0';
        FC2 <= '0';
        FCD1 <= '0';
        FCU1 <= '0';
        GT0 <= '0';
        GT1 <= '0';
        GT2 <= '0';
        wait for TbPeriod;
        --Scenario 13
        
        -- Stop the clock and hence terminate the simulation
        TbSimEnded <= '1';
        wait;
    end process;

end tb;

-- Configuration block below is required by some simulators. Usually no need to edit.

configuration cfg_tb_design_1_wrapper of tb_design_1_wrapper is
    for tb
    end for;
end cfg_tb_design_1_wrapper;